# Generated by Django 6.0.8 on 2026-08-08 17:01

import common.validators
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InternshipProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('role', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('duration_weeks', models.PositiveIntegerField()),
                ('department', models.CharField(max_length=255)),
                ('weekly_hours', models.PositiveIntegerField()),
                ('maximum_interns', models.PositiveIntegerField()),
                ('skills_needed', models.JSONField(blank=True, default=list)),
                ('skills_to_develop', models.JSONField(blank=True, default=list)),
                ('goals', models.TextField(blank=True)),
                ('expected_outcome', models.TextField(blank=True)),
                ('final_project', models.TextField(blank=True)),
                ('additional_instructions', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('ARCHIVED', 'Archived'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mentor', models.ForeignKey(limit_choices_to={'role': 'MENTOR'}, on_delete=django.db.models.deletion.PROTECT, related_name='programs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='InternProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.CharField(blank=True, max_length=255)),
                ('university', models.CharField(blank=True, max_length=255)),
                ('learning_goals', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mentor', models.ForeignKey(limit_choices_to={'role': 'MENTOR'}, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_interns', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'INTERN'}, on_delete=django.db.models.deletion.CASCADE, related_name='intern_profile', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interns', to='programs.internshipprogram')),
            ],
            options={
                'ordering': ['user__full_name'],
            },
        ),
        migrations.CreateModel(
            name='ProgramReferenceMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('resource_type', models.CharField(choices=[('PDF', 'PDF'), ('DOC', 'DOC'), ('DOCX', 'DOCX'), ('PPT', 'PPT'), ('PPTX', 'PPTX'), ('IMAGE', 'Image'), ('ZIP', 'ZIP'), ('LINK', 'Link')], max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='program_materials/', validators=[common.validators.validate_upload_file])),
                ('external_url', models.URLField(blank=True)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_materials', to='programs.internshipprogram')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='InternSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100)),
                ('skill_level', models.PositiveSmallIntegerField(choices=[(1, 'Beginner'), (2, 'Basic'), (3, 'Intermediate'), (4, 'Advanced'), (5, 'Expert')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('intern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='programs.internprofile')),
            ],
            options={
                'ordering': ['skill_name'],
                'constraints': [models.UniqueConstraint(fields=('intern', 'skill_name'), name='unique_intern_skill_name')],
            },
        ),
    ]
