# Generated by Django 6.0.8 on 2026-08-08 17:01

import common.validators
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programs', '0001_initial'),
        ('roadmaps', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('difficulty', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], max_length=20)),
                ('estimated_time_minutes', models.PositiveIntegerField()),
                ('deliverable', models.TextField(blank=True)),
                ('success_criteria', models.TextField(blank=True)),
                ('due_date', models.DateField()),
                ('requirement_type', models.CharField(choices=[('REQUIRED', 'Required'), ('OPTIONAL', 'Optional')], default='REQUIRED', max_length=20)),
                ('source', models.CharField(choices=[('AI_GENERATED', 'AI Generated'), ('MANUAL', 'Manual')], default='MANUAL', max_length=20)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='programs.internshipprogram')),
                ('roadmap_week', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='roadmaps.roadmapweek')),
            ],
            options={
                'ordering': ['display_order', 'due_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='TaskResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('resource_type', models.CharField(choices=[('PDF', 'PDF'), ('DOC', 'DOC'), ('DOCX', 'DOCX'), ('PPT', 'PPT'), ('PPTX', 'PPTX'), ('IMAGE', 'Image'), ('ZIP', 'ZIP'), ('LINK', 'Link')], max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='task_resources/', validators=[common.validators.validate_upload_file])),
                ('external_url', models.URLField(blank=True)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='tasks.task')),
            ],
            options={
                'ordering': ['display_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='TaskAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('TO_DO', 'To Do'), ('IN_PROGRESS', 'In Progress'), ('SUBMITTED', 'Submitted'), ('NEEDS_REVISION', 'Needs Revision'), ('COMPLETED', 'Completed')], default='TO_DO', max_length=20)),
                ('due_date_override', models.DateField(blank=True, null=True)),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('mentor_feedback', models.TextField(blank=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('intern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_assignments', to='programs.internprofile')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='tasks.task')),
            ],
            options={
                'ordering': ['-assigned_at'],
                'constraints': [models.UniqueConstraint(fields=('task', 'intern'), name='unique_task_intern_assignment')],
            },
        ),
    ]
