# Generated by Django 6.0.8 on 2026-08-08 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Roadmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('assignment_scope', models.CharField(choices=[('PROGRAM', 'Entire Program'), ('GROUP', 'Selected Interns'), ('INDIVIDUAL', 'Individual Intern')], default='PROGRAM', max_length=20)),
                ('number_of_weeks', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('generated_by_ai', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'MENTOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_roadmaps', to=settings.AUTH_USER_MODEL)),
                ('assigned_interns', models.ManyToManyField(blank=True, related_name='roadmaps', to='programs.internprofile')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmaps', to='programs.internshipprogram')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoadmapWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveIntegerField()),
                ('weekly_focus', models.CharField(max_length=255)),
                ('learning_objectives', models.JSONField(blank=True, default=list)),
                ('expected_skills_gained', models.JSONField(blank=True, default=list)),
                ('mentor_notes', models.TextField(blank=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('roadmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='roadmaps.roadmap')),
            ],
            options={
                'ordering': ['display_order', 'week_number'],
                'constraints': [models.UniqueConstraint(fields=('roadmap', 'week_number'), name='unique_roadmap_week_number')],
            },
        ),
    ]
